public with sharing class YINMonitorLogWrap {
    public String request;
    public String response;
    public String statusCode;
    public String apexClass;
    public String recordId;
    public String module;
    public String userId;
    public String message;
    public String typeOfIntegration;
    public String method;
    public String requestURL;
    public String remoteAddress;
    public String headers;
    public String dataSource;
    public String externalSystemName;
    public Exception exObj;
}